#!/usr/bin/env python
#-*- mode: python -*-

import sys
import json
import logging
import argparse

from bibframe.reader import bfconvert
from amara3.inputsource import inputsourcetype


def run(inputs=None, base=None, out=None, limit=None, rdfttl=None, rdfxml=None, xml=None,
        config=None, verbose=False, mods=None, modfiles=None, canonical=False, lax=False):
    '''
    Basically takes parameters typical for command line invocation and adapts them for use in the API

    '''
    if config is None:
        config = {}
    else:
        config = json.load(config)

    logger = logging.getLogger('marc2bf')
    if verbose:
        logger.setLevel(logging.DEBUG)

    for mod in mods:
        __import__(mod, globals(), locals(), [])

    for modfile in modfiles:
        with open(modfile) as f:
            code = compile(f.read(), modfile, 'exec')
            exec(code, globals(), locals())

    bfconvert(inputs=inputs, entbase=base, out=out, limit=limit, rdfttl=rdfttl, rdfxml=rdfxml,
                xml=xml, config=config, verbose=verbose, canonical=canonical, logger=logger,
                lax=lax, defaultsourcetype=inputsourcetype.filename)
    return


if __name__ == '__main__':
    #marc2bf -v test/resource/700t.mrx
    #marc2bf -v -o /dev/null --rdfttl /tmp/foo.ttl test/resource/700t.mrx
    #parser = argparse.ArgumentParser(prog="bootstrap", add_help=False)
    parser = argparse.ArgumentParser()
    parser.add_argument('inputs', metavar='inputs', nargs='*',
                        help='One or more MARC/XML files to be parsed and converted to BIBFRAME RDF.')
    parser.add_argument('-o', '--out', type=argparse.FileType('w'), default=sys.stdout,
        help='File where raw Versa JSON output should be written'
             '(default: write to stdout)')
    parser.add_argument('-p', '--postout', metavar="IRI",
        help='HTTP endpoint for pushing or posting raw Versa JSON output'
             '(default: write to stdout)')
    parser.add_argument('--rdfttl', type=argparse.FileType('wb'),
        help='File where RDF Turtle output should be written')
    parser.add_argument('--rdfxml', type=argparse.FileType('wb'),
        help='File where RDF XML output should be written')
    parser.add_argument('--xml', type=argparse.FileType('w'),
        help='File where MicroXML output should be written')
    parser.add_argument('-c', '--config', type=argparse.FileType('r'),
        help='File containing config in JSON format')
    #parser.add_argument('-s', '--stats', type=argparse.FileType('w'),
    #    help='file where statistics output should be written in JSOn format')
    parser.add_argument('-l', '--limit', metavar="NUMBER",
        help='Limit the number of records processed to this number. If omitted, all records will be processed.')
    parser.add_argument('-b', '--base', metavar="IRI", #dest="base",
        help='Base IRI to be used for creating resources.')
    parser.add_argument('--mod', metavar="PYMODULE", nargs="*", action='append',
        help='Python module to be imported in order to register plugins (can be specified multiple times.')
    parser.add_argument('--modfile', metavar="FILEPATH", nargs="*", action='append',
        help='Python file to be executed as a module in order to register plugins (can be specified multiple times.')
    parser.add_argument('-v', '--verbose', action='store_true',
        help='Show additional messages and information')
    parser.add_argument('--canonical', action='store_true',
        help='Use Versa\'s canonical form for output. Warning: memory inefficient')
    parser.add_argument('--lax', action='store_true',
        help='Parse less strictly, e.g. accepting MARC/XML with bad namespace declarations')
    #XXX: Any way to get generalized archive support using shutil? Perhaps along with tempfile?
    #https://docs.python.org/3/library/shutil.html#archiving-operations
    #parser.add_argument('-z', '--zipcheck', action='store_true',
    #    help='Check for zip files among the inputs')
    #
    args = parser.parse_args()
    args.mod = [i for items in args.mod or [] for i in items]
    args.modfile = [i for items in args.modfile or [] for i in items]

    run(inputs=args.inputs, base=args.base, out=args.out, limit=args.limit, rdfttl=args.rdfttl,
        rdfxml=args.rdfxml, xml=args.xml, config=args.config, verbose=args.verbose,
        mods=args.mod, modfiles=args.modfile, canonical=args.canonical, lax=args.lax)
    #for f in args.inputs: f.close()
    if args.rdfttl: args.rdfttl.close()
    if args.rdfxml: args.rdfxml.close()
    args.out.close()
